name: flutter_web_socket
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  web_socket_channel: ^2.1.0
  get:
  json_annotation: ^4.4.0
  flutter_webrtc: ^0.7.0+hotfix.1
  shared_preferences: ^2.0.7
  http: ^0.13.4
  path_provider: ^2.0.2
  uuid: ^3.0.5
  permission_handler: ^8.3.0
  stream_channel: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner:
  flutter_gen_runner:
  json_serializable: ^6.1.3

flutter:
  uses-material-design: true
